# fly.toml app configuration file generated for estimate-work on 2024-09-07T09:01:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'estimate-work'
primary_region = 'ams'

[build]
    [build.args]
        GO_VERSION = '1.23.0'

[env]
    LISTEN = ':8080'

[http_service]
    internal_port = 8080
    force_https = true
    auto_stop_machines = 'suspend'
    auto_start_machines = true
    min_machines_running = 0
    processes = ['app']

[[vm]]
    size = 'shared-cpu-1x'
